### ISSUE TITLE
mpris.org website compromised?

### ISSUE THREAD

**Issue by wayneoutthere** [xmms2/wiki#2]
was reading this [article](http://www.pro-linux.de/news/1/25784/kde-connect-erh%C3%83%C2%A4lt-nautilus-anbindung.html) to find out what is MPRIS and when i searched i found this [github page](https://github.com/xmms2/wiki/wiki/MPRIS) 
When you click on the mpris.org link it takes you correctly here to xmms.  
however, the mpris.org website seems compromised/cracked/malicious
I'm alerting you on this since when I was referencing the project it was pulling this meta data into my posts and it looked bad.  
Thanks and hope this helps.

**Comment by nesciens** [comment]
mpris.org indeed seems defunct. I've updated the link on https://github.com/xmms2/wiki/wiki/MPRIS to point at https://www.freedesktop.org/wiki/Specifications/mpris-spec/. Based on a grep of the wiki repo, I do not believe we have other references to mpris.org.
